# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83f8a32dae9b9bde5606af801b5154dc7343e30f1432187e3b0c40b34abac29fe52aa7ab697de0ef74d6d7e9797d5852d421ee387c3e848889dc52c0280f1854

test:
  secret_key_base: d0558379a2a51a48dbf3ad6ddf92799e4033b57a7a8d4ba6265572e74824b9219f9a0b4cf580d0bf0b9dd353698082e104b821bef44d4803b61ba8e299bad799

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
